/**
 * AES-256-GCM encryption helper — used for mailbox credentials (app passwords, OAuth refresh
 * tokens) and `AiProviderKey.apiKeyEncrypted`.
 *
 * Format produced by `encrypt()`: `<ivHex>:<authTagHex>:<ciphertextHex>` — a single string that's
 * easy to store in one Postgres column and trivially reversible by `decrypt()`.
 *
 * The encryption key (`MAILBOX_CREDENTIAL_KEY`) is a 32-byte key, base64 or hex encoded, supplied
 * via env var and generated by `scripts/install.sh` with `openssl rand -base64 32` — it is never
 * hardcoded and never committed.
 */
import { createCipheriv, createDecipheriv, randomBytes, timingSafeEqual } from 'node:crypto';

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH_BYTES = 12; // 96-bit IV is the recommended size for GCM
const KEY_LENGTH_BYTES = 32; // AES-256

export class EncryptionKeyError extends Error {}

/** Normalizes a base64- or hex-encoded key string into a 32-byte Buffer. Throws
 *  `EncryptionKeyError` if the decoded key isn't exactly 32 bytes. */
export function loadEncryptionKey(rawKey: string): Buffer {
  if (!rawKey || rawKey.trim().length === 0) {
    throw new EncryptionKeyError('Encryption key is empty. Set MAILBOX_CREDENTIAL_KEY.');
  }

  const candidates: Buffer[] = [];
  // Try base64 first (install.sh generates keys this way), fall back to hex.
  try {
    candidates.push(Buffer.from(rawKey, 'base64'));
  } catch {
    /* ignore */
  }
  try {
    candidates.push(Buffer.from(rawKey, 'hex'));
  } catch {
    /* ignore */
  }

  const validKey = candidates.find((buf) => buf.length === KEY_LENGTH_BYTES);
  if (!validKey) {
    throw new EncryptionKeyError(
      `Encryption key must decode to exactly ${KEY_LENGTH_BYTES} bytes (base64 or hex). ` +
        `Generate one with: openssl rand -base64 32`,
    );
  }
  return validKey;
}

/** Encrypts `plaintext` with AES-256-GCM under `key` (a raw 32-byte Buffer, see
 *  `loadEncryptionKey`). Returns `ivHex:authTagHex:ciphertextHex`. */
export function encrypt(plaintext: string, key: Buffer): string {
  if (key.length !== KEY_LENGTH_BYTES) {
    throw new EncryptionKeyError(`Key must be ${KEY_LENGTH_BYTES} bytes, got ${key.length}`);
  }
  const iv = randomBytes(IV_LENGTH_BYTES);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return `${iv.toString('hex')}:${authTag.toString('hex')}:${ciphertext.toString('hex')}`;
}

/** Decrypts a string produced by `encrypt()`. Throws if the payload is malformed or the auth tag
 *  doesn't verify (tampered ciphertext or wrong key). */
export function decrypt(payload: string, key: Buffer): string {
  if (key.length !== KEY_LENGTH_BYTES) {
    throw new EncryptionKeyError(`Key must be ${KEY_LENGTH_BYTES} bytes, got ${key.length}`);
  }
  const parts = payload.split(':');
  if (parts.length !== 3) {
    throw new Error('Malformed encrypted payload: expected ivHex:authTagHex:ciphertextHex');
  }
  const [ivHex, authTagHex, ciphertextHex] = parts;
  const iv = Buffer.from(ivHex, 'hex');
  const authTag = Buffer.from(authTagHex, 'hex');
  const ciphertext = Buffer.from(ciphertextHex, 'hex');

  if (iv.length !== IV_LENGTH_BYTES) {
    throw new Error(`Malformed IV: expected ${IV_LENGTH_BYTES} bytes, got ${iv.length}`);
  }

  const decipher = createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  return plaintext.toString('utf8');
}

/** Masks a decrypted secret for display in the dashboard (e.g. `GET /ai-providers` list view) —
 *  shows only the last 4 characters, matching the "masked key" requirement in Phase 3. */
export function maskSecret(secret: string, visibleTrailingChars = 4): string {
  if (secret.length <= visibleTrailingChars) {
    return '*'.repeat(secret.length);
  }
  const visible = secret.slice(-visibleTrailingChars);
  return `${'*'.repeat(Math.max(secret.length - visibleTrailingChars, 8))}${visible}`;
}

/** Constant-time string comparison, used for callback-secret header checks
 *  (`/internal/ai/personalize`, `/internal/ai/classify-reply`) so a timing side-channel can't leak
 *  the secret one byte at a time. */
export function safeCompare(a: string, b: string): boolean {
  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');
  if (bufA.length !== bufB.length) {
    // Still run a comparison of equal-length buffers to avoid a length-based timing signal.
    timingSafeEqual(bufA, bufA);
    return false;
  }
  return timingSafeEqual(bufA, bufB);
}
